when:
  branch: [main]
  event: [push, manual]

steps:
  - name: build-frontend
    image: plugins/docker
    depends_on: []
    settings:
      repo: 192.168.1.101:5000/kuukan-app/juicer-frontend
      registry: 192.168.1.101:5000
      insecure: true
      dockerfile: src/client.Dockerfile
      context: src/
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      build_args:
        - VITE_BACKEND_URI=https://juicer.kuukan.dev/backend
        - VITE_API_ENDPOINT=https://discord.com/api/v10
        - VITE_CLIENT_ID=1413382444882858024
        - "VITE_BOT_INSTALL_URI=https://discord.com/oauth2/authorize?client_id=1413382444882858024&permissions=268438576&integration_type=0&scope=bot"
        - "VITE_USER_AUTH_URI=https://discord.com/oauth2/authorize?client_id=1413382444882858024&response_type=code&redirect_uri=https%3A%2F%2Fjuicer.kuukan.dev%2Fbackend%2Fdiscord%2Fauth%2Fcallback&scope=identify"

  - name: build-backend
    image: plugins/docker
    depends_on: []
    settings:
      repo: 192.168.1.101:5000/kuukan-app/juicer-backend
      registry: 192.168.1.101:5000
      insecure: true
      dockerfile: src/server.Dockerfile
      context: src/
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: build-db
    image: plugins/docker
    depends_on: []
    settings:
      repo: 192.168.1.101:5000/kuukan-app/juicer-db
      registry: 192.168.1.101:5000
      insecure: true
      dockerfile: src/db.Dockerfile
      context: src/
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: deploy
    image: appleboy/drone-ssh
    depends_on: [build-frontend, build-backend, build-db]
    settings:
      host: 192.168.1.101
      username: kuukan
      key:
        from_secret: ssh_key
      command:
        - cd ~/projects/apps/juicer && docker compose pull && docker compose up -d
