
services:
  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.5.2
    container_name: juicer_traefik
    restart: always
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false  # Secure dashboard access
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --global.sendanonymoususage=false
    ports:
      - "80:80"   # HTTP - will redirect to HTTPS
      - "443:443" # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      # HTTP to HTTPS redirect
      - traefik.http.routers.http-redirect.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.http-redirect.entrypoints=web
      - traefik.http.routers.http-redirect.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # Secure dashboard access
      - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_AUTH}
      - traefik.http.routers.dashboard.middlewares=dashboard-auth

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: juicer_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data
      - ./juicer-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # SECURITY: Remove port exposure - database should only be accessible internally
    expose:
      - '${POSTGRES_PORT}' # expose port to linked services only
    command: -p ${POSTGRES_PORT}

  # Backend Service
  backend:
    build: ./juicer-backend
    container_name: juicer_backend
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db # Ensures the 'db' service starts before the 'backend'
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.http.routers.backend.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/backend`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend
      - traefik.http.middlewares.backend-security.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.backend-security.headers.customrequestheaders.X-Forwarded-For=""
      - traefik.http.middlewares.backend-security.headers.customrequestheaders.X-Real-IP=""
      - traefik.http.routers.backend.middlewares=backend-stripprefix,backend-security

  # Frontend Service
  frontend:
    build:
      context: ./juicer-frontend
      args:
        VITE_BACKEND_URI: ${VITE_BACKEND_URI}
        VITE_BOT_INSTALL_URI: ${VITE_BOT_INSTALL_URI}
        VITE_USER_AUTH_URI: ${VITE_USER_AUTH_URI}
        VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
    container_name: juicer_frontend
    restart: always
    env_file:
      - ./.env
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend.priority=1
      # Security headers for frontend
      - traefik.http.middlewares.frontend-security.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.frontend-security.headers.customrequestheaders.X-Forwarded-For=""
      - traefik.http.middlewares.frontend-security.headers.customrequestheaders.X-Real-IP=""
      - traefik.http.middlewares.frontend-security.headers.customresponseheaders.X-Frame-Options=DENY
      - traefik.http.middlewares.frontend-security.headers.customresponseheaders.X-Content-Type-Options=nosniff
      - traefik.http.middlewares.frontend-security.headers.customresponseheaders.X-XSS-Protection=1;mode=block
      - traefik.http.middlewares.frontend-security.headers.customresponseheaders.Referrer-Policy=strict-origin-when-cross-origin
      - traefik.http.routers.frontend.middlewares=frontend-security

volumes:
  postgres_data: # Defines the named volume for data persistence
  traefik_letsencrypt: # Defines the named volume for Let's Encrypt certificates