
services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: juicer_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data
    ports:
      - '8008:8008' # Expose port to host for development/debugging
    command: -p 8008

  # Backend Service
  backend:
    build: ./juicer-backend
    container_name: juicer_backend
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./juicer-backend/.env
    environment:
      # Pass database connection details to the backend
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db # Ensures the 'db' service starts before the 'backend'

  # Frontend Service
  frontend:
    build: ./juicer-frontend
    container_name: juicer_frontend
    restart: always
    env_file:
      - ./juicer-frontend/.env
    ports:
      - '8080:8080' # Map container's port 8080 to host's port 8080
    depends_on:
      - backend

volumes:
  postgres_data: # Defines the named volume for data persistence