
services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: juicer_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data
      - ./juicer-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}' # Expose port to host for development/debugging
    expose:
      - '${POSTGRES_PORT}' # expose port to linked services
    command: -p ${POSTGRES_PORT}

  # Backend Service
  backend:
    build: ./juicer-backend
    container_name: juicer_backend
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./juicer-backend/.env
      - ./.env
    depends_on:
      - db # Ensures the 'db' service starts before the 'backend'

  # Frontend Service
  frontend:
    build: ./juicer-frontend
    container_name: juicer_frontend
    restart: always
    env_file:
      - ./juicer-frontend/.env
    ports:
      - '8080:8080' # Map container's port 8080 to host's port 8080
    depends_on:
      - backend

volumes:
  postgres_data: # Defines the named volume for data persistence